### ISSUE TITLE
Every mmo* has its own folder, can they all use the same one please?

### ISSUE THREAD

**Issue by ZeroEcks** [mmoMinecraftDev/mmoCore#10]
Its just hard to do things when i have to navigate to a new folder every time.

**Comment by Salynne** [comment]
I thought it was like this, isn't there a setting in the config for this?

**Comment by ZeroEcks** [comment]
No there isn't one i can see, Would you like me to post my config?

**Comment by Salynne** [comment]
Go for it. I haven't actually looked at this project in quite a while, I'm not the main dev. I just remember telling @Rycochet months ago it should be like you said.

**Comment by Rycochet** [comment]
It's actually simpler than this - create a "plugins/mmoMinecraft" folder, everything will automatically move over to that and use it instead.

It's actually mentioned here - http://dev.bukkit.org/server-mods/mmocore/#w-data-folder
