### ISSUE TITLE
mmoCore not reading chat color permissions

### ISSUE THREAD

**Issue by Dockter** [mmoMinecraftDev/mmoCore#12]
Tested this on Group Manager, bPermissions and a basic permissions.yml of CraftBukkit, all failed.

Config file has this line:
- admin.title=BLUE

Users.yml file contains this line under permissions:
- admin.title

Fails to display the chat color in blue, mmoChatTitle also has the same issue.

**Comment by Xaymar** [comment]
Will check this out.

**Comment by Dockter** [comment]
This has been fixed.
