### ISSUE TITLE
mmoCore Math error?  CB++

### ISSUE THREAD

**Issue by Dockter** [mmoMinecraftDev/mmoCore#13]
Getting the following error using CB++ 54, not sure if this was a SpoutAPI change, I asked Afforess, Wolfspider commented (in chat) that you didn't know math?

http://www.pastie.org/3285017

Getting thousands of these spammed on server console once a user logs in.

**Comment by Rycochet** [comment]
Probably some API changes, I need to update pom files and rebuild everything...

**Comment by Dockter** [comment]
Any idea on when you might have a chance to get to this?

**Comment by Rycochet** [comment]
Hopefully this evening - only had a short amount of time for myself since the weekend (and about to be out for the day again) -  but I'm hopeful for this evening lol...

**Comment by Rycochet** [comment]
Just pushed the fix, should be there as soon as it finishes building.
