### ISSUE TITLE
GenericGradient default size error.

### ISSUE THREAD

**Issue by Dockter** [mmoMinecraftDev/mmoCore#14]
Could you please be so kind to set the default value this is looking for?

2012-01-31 15:38:40 [WARNING] GenericGradient belonging to mmoTarget does not have a default size!

**Comment by Xaymar** [comment]
I'm going to claim this was fixed by Commit cab273c7eee47e18269f128f7e3f2253317167a6

**Comment by Dockter** [comment]
For what its worth from time to time Im seeing the exact same error but with mmoChat not having a default size.
