### ISSUE TITLE
Error Spam from mmoCore/mmoTarget

### ISSUE THREAD

**Issue by phatchico** [mmoMinecraftDev/mmoCore#18]
This spams my console whenever someone has another player targeted or a Citizens npc, any help would be appreciated.  Thanks.

17:06:01 [SEVERE] java.lang.ArithmeticException: / by zero
17:06:01 [SEVERE]       at mmo.Core.MMO.getArmor(MMO.java:114)
17:06:01 [SEVERE]       at mmo.Core.gui.GenericLivingEntity.getBottomValue(Gener
icLivingEntity.java:189)
17:06:01 [SEVERE]       at mmo.Core.gui.GenericLivingEntity.onTick(GenericLiving
Entity.java:246)
17:06:01 [SEVERE]       at mmo.Target.MMOTarget$perPlayer.onTick(MMOTarget.java:
134)
17:06:01 [SEVERE]       at org.getspout.spoutapi.gui.GenericScreen.onTick(Generi
cScreen.java:143)
17:06:01 [SEVERE]       at org.getspout.spoutapi.gui.InGameScreen.onTick(InGameS
creen.java:69)
17:06:01 [SEVERE]       at org.getspout.spout.player.SpoutCraftPlayer.onTick(Spo
utCraftPlayer.java:1219)
17:06:01 [SEVERE]       at org.getspout.spout.ServerTickTask.run(ServerTickTask.
java:41)
17:06:01 [SEVERE]       at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainT
hreadHeartbeat(CraftScheduler.java:137)
17:06:01 [SEVERE]       at net.minecraft.server.MinecraftServer.w(MinecraftServe
r.java:503)
17:06:01 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftSer
ver.java:435)
17:06:01 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(Sour
ceFile:465)

**Comment by Rycochet** [comment]
Was fixed in the dev builds a week ago - http://files.mmo.me.uk/dev/

**Comment by phatchico** [comment]
ah awesome!  I'll give those a try tonight.  Thanks for your help!

**Comment by lukespragg** [comment]
Assuming this is resolved, as there has been no comments in months.
