### ISSUE TITLE
Are you planning to do an update for R5 Event System?

### ISSUE THREAD

**Issue by Dockter** [mmoMinecraftDev/mmoCore#19]
I was curious if you folks had planned to do the event system update required in R5 of CB so that these plugins are compatible with MC 1.2 ?

Thanks!

**Comment by Rycochet** [comment]
Not really been around to hear anything about this - got a link for me?

Currently it works with the new ones (even without being rebuilt) - so any major changes like that need to be fixed.

Not got that much time right now, but I will fix things as soon as I know what's happening.

**Comment by Dockter** [comment]
http://wiki.bukkit.org/Introduction_to_the_New_Event_System#Creating_Custom_Events

**Comment by Dockter** [comment]
?

**Comment by Rycochet** [comment]
I did see, and just need the time to update now - seems nice and simple to use :-)

**Comment by Pamelloes** [comment]
Several of the plugins have been updated, though issues with Jenkins mean that you will have to build them yourself.

**Comment by lukespragg** [comment]
http://build.spout.org/view/mmoMinecraft has all the builds available for ones that have been updated. :)
