### ISSUE TITLE
Version 1.2.3 NPE

### ISSUE THREAD

**Issue by Dockter** [mmoMinecraftDev/mmoCore#22]
Ive been watching your mmoMinecraftdev builds for mmoCore.

Just did a pull and compiled, here's an error upon server launch.

6:19:09 PM [SEVERE] Error occurred while enabling mmoCore v2.3 (Is it up to date?)
6:19:09 PM java.lang.NullPointerException
6:19:09 PM  at mmo.Core.MMOPlugin.onEnable(MMOPlugin.java:199)
6:19:09 PM  at mmo.Core.MMOCore.onEnable(MMOCore.java:97)
6:19:09 PM  at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
6:19:09 PM  at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
6:19:09 PM  at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:363)
6:19:09 PM  at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:342)
6:19:09 PM  at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:324)
6:19:09 PM  at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:422)
6:19:09 PM  at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:409)
6:19:09 PM  at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:223)
6:19:09 PM  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:477)
6:19:09 PM  at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)

**Comment by Rycochet** [comment]
I've not actually got a working test environment right now - but doing some cleaning up inside it and just pushed changes - will almost certainly break other mmo\* plugins, but they're next list to be fixed...

**Comment by Fureniku** [comment]
I'm more than happy to do testing if you want, I have a local system on my computer I use purely for testing plugins and configuring before a live install :) I'll keep an eye on the dev page as I said, but obviously I'll know quicker if you reply here so I get a lovely email :P

**Comment by Dockter** [comment]
Any update on this?

**Comment by Fureniku** [comment]
He has updated mmoCORE to 1.2.3 but nothing else - so its of no use until he gets the chance to do the rest. I know he's busy with real life stuff and also the spout official GUI system, so we'll just need to be patient :)

When he does update I plan on doing a few addons for mmoInfo - especially as compass and coords will be obsolete now due to the new compass/map on spoutcraft

**Comment by Dockter** [comment]
mmoCore hasn't been updated actually.  Armed_Troop is working on it and even the configuration setup reflects the old setup.

**Comment by Fureniku** [comment]
Rycochet said on the official forums core is updated but he hasn't let it compile because it'd break the other plugins - he posts every few days im sure he'd mention if he have someone permission to take over..

**Comment by Dockter** [comment]
If it wasn't so awesome, I wouldn't want it so bad.

**Comment by Rycochet** [comment]
As soon as I get the time to update things I'll do the rest of them, just that I really can't let _any_ of them build till they're all updated or it'll just mean broken plugins :-/

Currently mmoCore and mmoChat have been updated, but none of the others.

**Comment by Fureniku** [comment]
OK. Out of interest though will the github source be up-to-date? That way I can build locally, and once Info is ready I can do those extra plugins :D (And attempt to update the info-related ones if needs be)

**Comment by Rycochet** [comment]
Yep - there'll be more commits to mmoCore I fix other plugins and the API files get updated, but the functional bits are all done already.

**Comment by Dockter** [comment]
The git version thats posted is missing the configuration update.

**Comment by Dockter** [comment]
This has been fixed.
