### ISSUE TITLE
Please work on mmoQuest :)

### ISSUE THREAD

**Issue by wassilij** [mmoMinecraftDev/mmoCore#8]
Hey,

i think it would be awesome if you could start working on mmoQuest with Spout GUI :)

**Comment by Xaymar** [comment]
We will start working on this when both mmoMoney and mmoCore are completely done. We might need mmoNPC aswell later on, for roaming targets etc.

**Comment by lukespragg** [comment]
I'm sure they'll get to this ASAP. ;)
Right now it's a matter of getting current plugins updated.
