### ISSUE TITLE
mmoInfo and mmoParty gui issue

### ISSUE THREAD

**Issue by zbrain** [mmoMinecraftDev/mmoCore#9]
Hello, i just started using your plugin today in preparation for the final release of minecraft

i am currently running multiversefor a duel world set up and i notice that when ever i go threw
 a gate or teleport to another world that the gui for mmoinfo and mmoparty breaks. 

basically the party block disappears and the banner for mmoinfo disappears as well

i have to disconnect and reconnect for it to show back up again after i have loaded the other world

i am running bukkit 1185

and here is a screen shot of exactly what is happening:
http://entangled-life.com/mmoinfo.png

so i guess im wondering if this is fixable

thanks :)
zbrain

**Comment by Rycochet** [comment]
Actually that's a Spout bug, just done a workaround in the latest build of mmoCore - grab it from files.mmo.me.uk or just wait for the curse file to be approved ;-)

Hopefully there'll be an official fix in the next RB of Spout.

**Comment by zbrain** [comment]
that you so much :)

**Comment by zbrain** [comment]
i tried the dev build of spout and the mmo-core-dev and it still remains broken :(

i guess i can just hope for a fix soon :)

thanks again

**Comment by zbrain** [comment]
updated to 1.5 and it fixed it :) thank you so much

**Comment by zbrain** [comment]
yet it is still broken when ever i enter a portal, the nether portals work, but creative gates do not, thanks again :)

**Comment by Rycochet** [comment]
Bah, I'll change my workaround slightly.

It is fixed in Spout now - the next RB is due in 10 days or so, and then the workaround won't be needed :-)

**Comment by zbrain** [comment]
thanks man :) you rock
